name: Test Release Bundle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          echo "Ref: ${{ github.ref }}"
          aws/logs_monitoring/tools/build_bundle.sh ${{ github.ref }}